### ISSUE TITLE
Blue status bar

### ISSUE THREAD

**Issue by butzist** [butzist/ActivityLauncher#102]
Moved from #2 

The blue status bar and the fact that it can't be expanded to the notch area honestly makes the app look not great, especially on taller screens with 18.5:9 aspect ratio, I think that in code is called Action Bar, but I'm not sure, so you should probably look for that

**Comment by butzist** [comment]
@drogga I cannot reproduce this in Android Emulator with API 19, 21, and 30. Please provide screenshots and possibly a PR.

**Comment by drogga** [comment]
![Screenshot_20211231-113640_Activity Launcher](https://user-images.githubusercontent.com/53332345/147815777-5da8e896-babb-4ca6-ab63-ed60b0bcb2df.png)

**Comment by butzist** [comment]
API version? Manufacturer?

**Comment by drogga** [comment]
Samsung Galaxy S20 FE with API | SDK 30 = Android 11 (stock, no root), none of those matter, as I can install it on S20 with A.12 and S10 with A.11 and it will look exactly the same, also on other "modern" devices also with taller screens \ non-conventional aspect ratios from different brands, which I don't have on hand to test on currently, but I tested some time ago.

**Comment by butzist** [comment]
Well, on my phone (LineageOS API 30) and all emulator versions it looks like this:

![Screenshot_1640944827](https://user-images.githubusercontent.com/2405792/147817315-214e0915-9fa4-4bc9-b67b-666c2bd1bbb2.png)

Can you try to find out where this odd color comes from?

**Comment by drogga** [comment]
That's a screenshot from LineageOS 18.1 (A.11 R = API 30) on Samsung Galaxy S4 mini (GT-i9195):

![Screenshot_20211231-122708_Activity_Launcher](https://user-images.githubusercontent.com/53332345/147818545-53f97881-0df5-42f0-9ab0-4fd9e14fce1a.png)

Unfortunately No, I don't know the code, or how to code, just how to do some modifications over already compiled .apk, a few months ago I played with this project's theming in Android Studio and I remember that I managed to compile it for myself with dark theme which was missing then and it looked good, now I can't remember much, nor I know what I did and where the compiled and altered .apk is.

**Comment by butzist** [comment]
Hi @ismael034, I tested your PR and the dark mode still looks correct on my device and in emulator - unfortunately the light mode has too little contrast. In general, I would prefer to not override colors and use the system palette wherever possible.

![Screenshot_1641193482](https://user-images.githubusercontent.com/2405792/147906265-0fd9fc1c-9e31-4296-bd68-5dc940c0ae7e.png)

**Comment by Ismael034** [comment]
Hi,

I have made some changes in the code to reduce the blackness of disabled elements on the list. The `colorAccent` hasn't been touch so (for example) the lock icon color will change depending on the system settings pallete. My change basically affects the status bar in terms of pallete system colors.

Thanks!

**Comment by drogga** [comment]
@Ismael034 I will be testing, since I reported the issue {but didn't actually opened it}, but unfortunately I can't produce, compile / build a .apk artifact file, please check the PR where I explained and help if you can, butzist still didn't replied, maybe he forgot or is busy.
(You can even enable the actions in your fork and build a artifact .apk file, so I can DL to test it, or share some details on how to make it not fail by myself on my fork (which is currently not existing)
Thank you.

**Comment by drogga** [comment]
I will soon try to upload my take (mod) of v.1.9.2 .apk and screenshots, which looks and works perfectly, so you both can check what I did and get some ideas of what can be achieved by some simple edits, without the need of major UI/UX/Layout revamp.

**Comment by Ismael034** [comment]
> @Ismael034 I will be testing, since I reported the issue {but didn't actually opened it}, but unfortunately I can't produce, compile / build a .apk artifact file, please check the PR where I explained and help if you can, butzist still didn't replied, maybe he forgot or is busy. (You can even enable the actions in your fork and build a artifact .apk file, so I can DL to test it, or share some details on how to make it not fail by myself on my fork (which is currently not existing) Thank you.

I havent used github actions at all but just to make sure, you want github actions to generate an apk an be able to download it right?

**Comment by drogga** [comment]
YES !

**Comment by Ismael034** [comment]
I am trying to set up actions/upload-artifact@v2 and download-artifact@v2. Lets see if it works

**Comment by drogga** [comment]
IDK too... (more on this in the PR ‐>)

**Comment by drogga** [comment]
As I promised, here's my mod of v1.9.2, works perfectly on Android 11 _{it didn't allowed me to attach it as .apk, so I had to archive it in .zip}_:

[Activity Launcher (v.1.9.2 Build 17) {de.szalkowski.activitylauncher} [icon, rotation crash Fix + Dark Mod {by Me}] [4.0+] configChanges.zip](https://github.com/butzist/ActivityLauncher/files/7815266/Activity.Launcher.v.1.9.2.Build.17.de.szalkowski.activitylauncher.icon.rotation.crash.Fix.%2B.Dark.Mod.by.Me.4.0%2B.configChanges.zip)
![Screenshot_20220105-152930_Activity Launcher](https://user-images.githubusercontent.com/53332345/148226921-a9609847-0df0-4aa7-8d19-8d9941bef1a0.png)

**Comment by butzist** [comment]
Should be fixed in latest master/beta version - reopen if not
