### ISSUE TITLE
won't open most activities without root

### ISSUE THREAD

**Issue by rayhantajichalt** [butzist/ActivityLauncher#103]
in previous versions, i can open any activity without root permission.
but today i encountered this after update...
![Screenshot_20220101-130509_Activity Launcher](https://user-images.githubusercontent.com/35326882/147844992-303fcdb1-1dc0-42a3-9032-e81da28ca84a.jpg)
it said : cannot run program "su" - no such file or directory
now most activities that previously can open, cannot be opened.

device : galaxy A51 android 11 stock firmware

**Comment by butzist** [comment]
You can use the context menu and start as non-root. Unexported or disabled activities are started as root by default. 
In the future, we could add a root detection, to restore the old behaviour, if no su is found. What do you think?

**Comment by drogga** [comment]
@rayhantajichalt probably clicked on the ones with padlock icon, which are the ones that require root as this icon means that the activity is a private unexported one, which makes this issue invalid and if not proven otherwise - it will be closed.
(Tested with the latest build from the Action's workflows - v1.13.3 Build 27 - no such issue with the "normal" activities)

Did you changed the samsung's NavBar ?, because this is not how it usually looks by default, which means that you are not telling something and did modifications to your system, which may cause issues.

**Comment by tamilan007** [comment]
@rayhantajichalt 
Sir it is a nice feature though 
Some activities in launcher can lead to factory reset or some problems (if user have root atleast they could know what could the activities do)
Don't ask me how to do 
Btw i am a root user

**Comment by drogga** [comment]
@tamilan007
Can you pls test the root shortcuts and then deny/forbid the root access for A. L. and test tge regular activities in order to confirm that the OP's statement is invalid ?

**Comment by tamilan007** [comment]
@drogga  sir sorry for late reply i have my notification turned off
I have a work managed device when i try to open work setup from activity launcher 
It will create teo work profiles
Unfortunately it will hang the system in nect reboot and force us to factory reset 
By rescue party api

**Comment by tamilan007** [comment]
@drogga please simpler terms while speaking i am not a great understandder of english

**Comment by tamilan007** [comment]
@drogga ok thanks maybe helpful if allow access system apps for root users only

**Comment by butzist** [comment]
@tamilan007 Are you suggesting to introduce a blacklist of activities that should be forbidden from ActivityLauncher?

**Comment by tamilan007** [comment]
@butzist  yes sir it can be only access to root user only 
We are beleiving that root users will have more responsibility than others 
And have some idea what they are dealing with (this is not a character of general users if they mess with core system apps 
We all know the result )

**Comment by tamilan007** [comment]
@butzist  maybe allow all activities to root users (i think all root users will have some knowledge 😅😅; because they rooted their phone )
Will have some knowledge to mess and not mess stuffs 
!! in the end root users are solely responsible for their actions

**Comment by butzist** [comment]
@tamilan007  I added a root/su detection to the app  Now the options for launching activities as root should be hidden on non-rooted phones. Closing this ticket.
