### ISSUE TITLE
Improve design/usability of app

### ISSUE THREAD

**Issue by butzist** [butzist/ActivityLauncher#104]
The usability and design of the whole app is suboptimal - in particular the new features for starting private activities make the application difficult to understand. As I don't have the time&skill to fix it, we're looking for someone with UI/UX experience to join the project create a new design, or implement it directly.

**Comment by drogga** [comment]
> instead of context menu, navigate to a new summary/editing page that allows execution of all actions

What exactly do you mean by this, can you explain it better with more details, point to a example or show a concept image or something ?

**Comment by KastenTop** [comment]
> > instead of context menu, navigate to a new summary/editing page that allows execution of all actions
> 
> What exactly do you mean by this, can you explain it better with more details, point to a example or show a concept image or something ?

I.e material design 2 style. You know, bottom bar, rounded elements

**Comment by tamilan007** [comment]
Can you reduce the timing of app loading 
#request#suggestion 
It irrates every time it reloads after doing long job and coming back

**Comment by butzist** [comment]
Completed in v2
