### ISSUE TITLE
Search activities

### ISSUE THREAD

**Issue by JonnyTech** [butzist/ActivityLauncher#11]
Is there an option to search for specific activities without having to manually scroll through the list looking? If not, can I request it as an enhancement / feature request please.

**Comment by butzist** [comment]
Agree, that this would be very useful indeed. Will happily accept a pull request if someone implements this.

**Comment by butzist** [comment]
A search feature is now available in beta: https://play.google.com/apps/testing/de.szalkowski.activitylauncher

**Comment by JonnyTech** [comment]
Excellent, thank you. Cannot test as I do not use Google Play so shall wait until an apk is built or released.

**Comment by butzist** [comment]
Take the APK from here: https://github.com/butzist/ActivityLauncher/releases/tag/1.9.0

**Comment by JonnyTech** [comment]
Great work, it works well. Thank you for taking the time and effort to implement this. The only nitpick: When searching, can the nodes auto-expand? The search string is usually the intent but only the application names are shown. One has to open each node to view the text within to identify the required one.

**Comment by butzist** [comment]
Send me a pull request with your suggestion ;)

**Comment by JonnyTech** [comment]
The update with filtering is much better. Thanks again. Any possibility of changing the fixed value of 10 items to something configurable? Or have the sections counted so if node headers < value x then expand all.
