### ISSUE TITLE
Blue lock

### ISSUE THREAD

**Issue by EndreEndi** [butzist/ActivityLauncher#111]
Hi, what's the thing with the blue lock at 85% of the activities in the app?
How I can get over that and launch the activity anyway?
Thanks
Screenshots of what I mean:
![Screenshot_20220105-182620_Activity Launcher](https://user-images.githubusercontent.com/14347302/148252758-5d64ad46-9fe0-4b46-87e6-da08cbeca4e8.png)
![Screenshot_20220105-182603_Activity Launcher](https://user-images.githubusercontent.com/14347302/148252767-24d91e42-3fb5-4ef4-ab52-cc441a973a97.png)

**Comment by butzist** [comment]
Those are "private" activities. Some of them will start, if you are lucky (e.g. DeveloperSettingsActivity in the Settings App).

Most private activities will require a rooted device, though. The latest update allows you to use root access, if you have it.
