### ISSUE TITLE
FAQ creation 

### ISSUE THREAD

**Issue by omideleayo** [butzist/ActivityLauncher#12]
If I may, would love to add a FAQ document for this project.
If you agree it needs one, I would go ahead. 
If you disagree, it's all fine.

**Comment by omideleayo** [comment]
Cool, would do that soon.

**Comment by Shadowspear123** [comment]
Hi, so far the app looks great, however, I can't find the shortcuts after they have been created. Where does the application place the shortcuts after it is prompted to create one?
