### ISSUE TITLE
Change language within app

### ISSUE THREAD

**Issue by RozvM** [butzist/ActivityLauncher#122]
It would be nice to have the ability to change the language just for the application and not for the whole OS.

**Comment by butzist** [comment]
Is being worked on by @Ismael034  in context of #121. Would you like to test?

**Comment by RozvM** [comment]
Yes please!

**Comment by Ismael034** [comment]
Please note that the config menu is not finished yet so there are some issues. You can get the APK from the actions page in this repo

**Comment by butzist** [comment]
Just note that the debug builds have a different signature than the release, i.e. Android will warn about resettig the apps preferences on installation.

**Comment by RozvM** [comment]
Thanks for the help!
Can I leave feedback about the debug build somewhere?

**Comment by butzist** [comment]
You can do here or on Gitter, of you like

**Comment by butzist** [comment]
Implemented in latest master/beta version
