### ISSUE TITLE
Add the ability to launch an activity through a quick shortcut in the application

### ISSUE THREAD

**Issue by bzz11g** [butzist/ActivityLauncher#124]
Hi Adam!
The title may seem obscure or even stupid, but I will try to explain what feature I am asking for and why it is useful
To begin with, English is not my native language, so my expressions may seem strange
Now I have a Google Pixel 6 and it has a wonderful feature "Quick Tap" (Settings > System > Gestures)  this feature allows you to double-tap on the back panel to launch one of the preset actions or any custom application
![Screenshot_20220116-104012](https://user-images.githubusercontent.com/1549909/149652061-02fd3388-4467-4bc6-ad25-df10d58220f5.png)![Screenshot_20220116-104027](https://user-images.githubusercontent.com/1549909/149652063-2f6a11c2-6957-4c16-9d40-81b4be600cd5.png)
As you can see in the screenshot, I can choose an application "Activity Launcher", but when I perform the gesture, it will open app
Some other applications are customizable (see screenshot) and allow you to set a specific action from the selected application
1DM+ and Camera app for example (Gear icon)
![Screenshot_20220116-104040](https://user-images.githubusercontent.com/1549909/149652197-fee110fa-0be0-44bb-94fd-ab8a12fd57ce.png)![Screenshot_20220116-110601](https://user-images.githubusercontent.com/1549909/149652225-19f0c6fc-931d-430f-b75d-ab931c6df835.png)
these are the same functions that are available to the user after a long press on the application icon on the desktop
![1DM](https://user-images.githubusercontent.com/1549909/149652854-6f52d2b7-e464-431b-9c5f-65cd71c08e3f.png)![Camera](https://user-images.githubusercontent.com/1549909/149652857-4e368aea-c93d-4518-8b55-274e06e37c73.png)
So if you add the ability to create your own shortcuts for actions inside the application, you can take the program to a completely different level.
In my case, I'm trying to implement the ability to launch smart home control (google home), this function is available from the lock screen, and from quick settings, but it cannot be added to double tap on the back panel
![Screenshot_20220116-104233](https://user-images.githubusercontent.com/1549909/149653029-e3d943c6-27b9-4ea1-9cc8-b98adf240d68.png)
I found the desired system activity (com.android.systemui.controls.management.ControlsFavoritingActivity), but I can't add it in the gesture settings in any way
Adding such functionality to the application will greatly expand the scope of its application, and increase the audience that will have a powerful gesture customization tool, and not only on pixel phones.
I hope you are interested in my feature proposal and implement it in one of the next updates

**Comment by butzist** [comment]
I see what you mean - could be done in a similar way to the RootLauncherActivity, with the activity to-be-started set in preferences. Who wants to implement this?

**Comment by butzist** [comment]
tbh, I see such a feature more in an application like [Shortcut Maker](https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker&hl=en&gl=US). Will close, as there does not seem to be anyone willing to implement this.

**Comment by drogga** [comment]
@bzz11g
The activity you are trying to launch is private, at lease on Lineage 18.1 (Android 11), but if it's not for you and you can launch it with A.L., then a app can be created to launch it, which you can then select \ pick in the Quick Tap, or just try [TapTap](http://github.com/KieronQuinn/TapTap) , but again - it probably won't work if the activity is private or disabled and you don't have root access.
