### ISSUE TITLE
Shortcut to remote ADB command?

### ISSUE THREAD

**Issue by finnzz** [butzist/ActivityLauncher#127]
World it be possible to use ActivityLauncher to make a shortcut to an ADB command that is run on a remote device?

For example using ActivityLauncher with Remote ADB Shell to make a shortcut that runs an ADB command through Remote ADB Shell?

Or some other app that would make such a thing possible?

And without root access.

**Comment by butzist** [comment]
tbh, I see such a feature more in an application like [Shortcut Maker](https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker&hl=en&gl=US)

**Comment by finnzz** [comment]
> tbh, I see such a feature more in an application like [Shortcut Maker](https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker&hl=en&gl=US)

Thank you for the response.  I went ahead and gave Shortcut Maker another try.  I'll have to play with it around a bit to see if I can get it to make a connection with an app l like remote ADB Shell.
