### ISSUE TITLE
Can't Create Shortcut

### ISSUE THREAD

**Issue by foxtrotzer0** [butzist/ActivityLauncher#129]
I'm on Android 11 using a Xiaomi device. Unfortunately, I can't create shortcuts even if I edit the name and change the icon. I hope someday would be able to help me. Thank you!

**Comment by drogga** [comment]
On the app info screen you should have an extra permissions screen where you should allow the shortcuts creation, I don't think it's the app's fault, if I'm right please close this issue yourself or at least reply that it worked so we can close it.

Alternatively, you can try with other similar apps and let us know if A.L. still can't create one, but others do ;)

**Comment by drogga** [comment]
@foxtrotzer0
On the app info screen you should have an extra permissions screen where you should allow the shortcuts creation, I don't think it's the app's fault, if I'm right please close this issue yourself or at least reply that it worked so we can close it.

Alternatively, you can try with other similar apps and let us know if A.L. still can't create one, but others do ;)
