### ISSUE TITLE
App launcher stopped working

### ISSUE THREAD

**Issue by Sbiz85** [butzist/ActivityLauncher#155]
I had a email app launcher shortcut on my android home screen that would open the recently open apps + keyboard.

Today (May 6 '22) I quit and restarted my phone and suddenly the icon is dead. I've never experienced that before. It says "shortcut isn't available." I can't seem to get it to do what it used to do.

I wanted to let y'all know in case it's happening to others. Thank you for your work!

**Comment by lukmangjo** [comment]
`#155`

**Comment by lukmangjo** [comment]
> I had a email app launcher shortcut on my android home screen that would open the recently open apps + keyboard.
> 
> Today (May 6 '22) I quit and restarted my phone and suddenly the icon is dead. I've never experienced that before. It says "shortcut isn't available." I can't seem to get it to do what it used to do.
> 
> I wanted to let y'all know in case it's happening to others. Thank you for your work!

**Comment by lukmangjo** [comment]
[https://github.com/butzist/ActivityLauncher/issues/155#issue-1228299967](jo0823305347@gmail.com) #154
