### ISSUE TITLE
display how the application is moved to the drive 

### ISSUE THREAD

**Issue by VolkDem777** [butzist/ActivityLauncher#161]
Hello 👋
I have been using this application for a long time and not so long ago I started having a problem with displaying the way to move to a memory card. Selected All applications, but there are no buttons to move the application.

**Comment by drogga** [comment]
@VolkDem777 You mean a system's activity of a Chinese brand device that you used to be able to launch and now can't ?
...if YES, then this is not the app's fault (explained many times - in the closed issue tickets), the manufacturers doesn't want you to be able to do this, those activities are not fixed, they can change any time, like when you do updates, they are trying to kill-off the external SD Cards completely (software and hardware wise), the same as the 3.5mm jack/port, so we can't do anything about it.
