### ISSUE TITLE
Nokia T10 Tablet Issue

### ISSUE THREAD

**Issue by borobabe** [butzist/ActivityLauncher#172]
Device: Nokia T10 Tablet, running Android 12, with no root or other modifications.

Hello all.  I'm trying to use Activity Launcher to set my SD card as internal storage. However, I'm not certain as to which option I need to set to do this.  Some options seem to be locked, and I get java errors preventing them from starting.  Can someone guide me with what steps I need to take, or if another app may help me, please?

**Comment by drogga** [comment]
Those are private activities, you need to have root access !
Blame the manufacturer and Google.
