### ISSUE TITLE
Can't create activity shortcut 

### ISSUE THREAD

**Issue by iqfareez** [butzist/ActivityLauncher#173]
**Steps to reproduce:**
1. Launch app
1. Select activity
1. Tap create shortcut

**Expected behaviour:**
Shortcut is created in the homescren

**Actual behaviour:**
Creating shorcut toast appear. But the shortcut was never created.

**Video:**

https://user-images.githubusercontent.com/60868965/190152243-d310e76e-22b1-4004-9928-7582b6183355.mp4 

**Configuration** 
- Android 11
- Xiaomi Redmi Note 11

Permission already given.

![Screenshot_2022-09-14-20-11-36-723_com.google.android.permissioncontroller.jpg](https://user-images.githubusercontent.com/60868965/190154538-6db98bfc-c2c9-4cde-ade5-3f38a4e0c82d.jpg)

**Comment by drogga** [comment]
The second screenshot - this isn't the correct menu you should be looking for, this is just a list of the available permissions in the manifest, you need to better explore and get to know your device, the menu you need is a totally diff. one !

**Comment by andersharrison** [comment]
I have a Xiaomi Mi 10 Pro on MIUI 13 and I had this problem, however, it was simply a settings issue. 

**To resolve**: Within the "App Info" screen, go to "Other permissions". In there is a specific setting for "Home screen shortcuts". I imagine it'll be similar on most MIUI phones.

![Screenshot_2022-11-07-13-17-21-910-edit_com miui securitycenter sm](https://user-images.githubusercontent.com/6575784/200322667-67a84579-9b70-417a-86bd-b589d7a36c7f.jpg)

![Screenshot_2022-11-07-13-13-03-822_com miui securitycenter sm](https://user-images.githubusercontent.com/6575784/200322678-e86afcc2-49ed-45d2-a752-6a2ebbeef544.jpg)

**Comment by drogga** [comment]
@iqfareez please check the comment by @andersharrison
