### ISSUE TITLE
java.lang.SecurityException

### ISSUE THREAD

**Issue by kmand** [butzist/ActivityLauncher#176]
First time using the app. When I try to add Google Voice Search, I get java.lang.SecurityException. I don't know if its specific to this selection. How do I fix this?

**Comment by drogga** [comment]
@kmand
What do you mean by "add" ?, on Samsung (A.9 Pie), when I tap on the mic. button from the Samsung KB > it works, please provide LogCat and other device and OS details, also which KB app you used...
