### ISSUE TITLE
Shortcuts Don't Launch

### ISSUE THREAD

**Issue by docpomus** [butzist/ActivityLauncher#180]
On Samsung S22 Ultra
After downloading from Play Store, created home page  shortcut for Settings, "Keyboard List and Default".
When launch, just get message "App isn't installed ".
Same result for all shortcuts created.

**Comment by drogga** [comment]
A.13 right ?

**Comment by docpomus** [comment]
Correct

**Comment by drogga** [comment]
Then you should've checked the other issues before creating a new one, because there's already **Shortcuts broken in Android 13**, which is the same.

**Comment by docpomus** [comment]
Sorry, my first time posting on the forum
