### ISSUE TITLE
Not able to launch some activities as shortcuts, particularly those not of the main user

### ISSUE THREAD

**Issue by pressRtowin** [butzist/ActivityLauncher#193]
This may be multiple issues, but I'm not sure where each begins and ends if that makes sense. There are lots of similarities to the issues described here (https://github.com/butzist/ActivityLauncher/issues/171), but I also experienced some problems before updating to 13.

My main use case for Activity Launcher has been to launch hidden apps on the various user profiles I use simultaneously on my Samsung devices. To those of you who are not familiar with this, _this is not the same as traditional user accounts on Android_, as the apps in these profiles can be run _without logging out of the main account_. If you're familiar with Work Profiles, these work the same way, however rather than just being limited to your main profile and Work Profile, on Samsung phones, you can have two additional sets of apps via Secure Folder and Dual Messenger.

I have a copy of Activity Launcher installed on all 4 profiles (Main, Dual Messenger, Work, Secure Folder), and I can use it to reach usually inaccessible places (such as the Work Profile's settings app, from where I can properly set things like the aspect ratio and camera cutout settings for Work Profile apps).

For some reason, I've found that many activities can correctly be launched from within the respective instance of Activity Launcher, but once I add it as a shortcut to my home screen, it no longer functions. Since updating to Android 13, almost all shortcuts created from the 3 non-main instances of Activity Launcher give me the "App isn't installed." error, while a large number of shortcuts created from the Main profile instance also give me the same error. (And yes, I've recreated all shortcuts after updating).

I'm using the latest Play Store version (in the beta channel) as well, but this doesn't seem to make a difference. Any clue what's going on?

**Comment by drogga** [comment]
Does other similar apps work properly, like for example the one by /sdex/ActivityManager (available here on GitHub) ?

**Comment by pressRtowin** [comment]
@drogga 

I went and did some more thorough testing between four different apps (Shortcut Maker, App Manager, Activity Manager, and Activity Launcher) and have documented the results [here](https://imgur.com/a/YlyrcHt).

All four apps were installed on my Z Fold 4 running Android 13/One UI 5 a total of four times as mentioned above: on the Main user (User 0), within the Dual Messenger profile (User 95), within the Work profile (User 10), and within Secure Folder (User 150). I then created shortcuts for each of the following from all sixteen (four apps across four profiles) instances of the applications:

- `com.android.settings.homepage.SettingsHomepageActivity`
- `com.android.settings.Settings$FullScreenAppsSettingsActivity`
- `com.android.settings.Settings$CameraCutoutSettingsActivity`
- `com.android.settings.Settings$FrontScreenAppsSettingsActivity`
- `com.android.settings.Settings$AutoRotateAppsSettingsActivity`
- `com.android.settings.Settings$AppDashboardActivity`
- `com.android.settings.Settings$ManageApplicationsActivity`
- `com.android.settings.Settings$ManageDomainUrlsActivity`
- `com.android.settings.Settings$HighPowerApplicationsActivity`

When trying to launch these shortcuts, three possible behaviors were observed:

- The correct activity would launch
- An activity would launch, but not the correct one (this was always in the case of a shortcut intended to launch a Dual Messenger app incorrectly launching the Main profile app instead)
- Nothing would launch

The three behaviors have been denoted by a green, orange, and red circle respectively drawn around the shortcut which exhibited that behavior.

Note that I only tested launching activities from shortcuts on the home page, and not from within the app, as that is what matters the most (and I wouldn't really care too much if an activity could not be launched from within the app, so long as it launched correctly from the shortcut).

---

On an unrelated note, I seem to have found a bug in Activity Manager while doing all this. If you take any number of activities that share the same default name (for instance `com.android.settings.Settings$AppDashboardActivity`
and `com.android.settings.Settings$ManageApplicationsActivity` are both named "Apps") and try to add them as shortcuts without leaving the app (or without having the app open as a pop-up window; what matters is that the launcher is not visible), only one shortcut will have been made (for the activities that share a name) when returning to the launcher. Furthermore, if you *do* return to the launcher between each shortcut being made (or make the shortcuts while using Activity Launcher as a pop-up window), then multiple shortcuts will be made, however, all subsequent shortcuts after the first will behave as the first shortcut does, rather than launching their intended activities. Renaming the activities with shared names when creating the shortcuts avoids this (which is why in the tests above, each instance of `com.android.settings.Settings$AppDashboardActivity` from Activity Launcher was renamed to "App Dashboard".

**Comment by KaKi87** [comment]
Hello,
Any news on this ?
I'm experiencing the same issue with developer options.
Launching from app works fine, but launching from shortcut doesn't ("Please enable developer options first").
Yet launching from system settings works fine as well.
Thanks

**Comment by Sash0k** [comment]
@KaKi87 i shall try to digging this problem on next holidays

**Comment by drogga** [comment]
@Sash0k (Alex), I hope this means that you will eventually also contribute here with PRs, because else it would be \ it's pointless pointless commenting and promising things here that doesn't concern your repo, but doing fixes only there... ;)

**Comment by KaKi87** [comment]
I don't mind using a fork to get this fix if the original's maintainer doesn't care, which seems to be the case considering the absence of comment from them.

**Comment by Sash0k** [comment]
@drogga контрибютить вам в мейнлайн я не хочу. Меня не устраивает то, что овнер этого проекта @butzist удалил русский язык из проекта год назад.

То что вы сделали - это дискриминация, поэтому был сделан форк. Мое личное мнение - OSS вне политики, и должен оставаться вне политики.
Каналы распространения apk скоро будут добавлены, в принципе есть большие планы по улучшению приложки, но до ближайших праздничных недель в России свободного времени не будет.

**Comment by drogga** [comment]
@Sash0k
This is an English (American) site, owned by Microsoft, where the official language is English, so either respect that and type in English, or don't comment at all !

**Comment by Sash0k** [comment]
@drogga читай [правила](https://docs.github.com/en/site-policy/github-terms) гитхаба

**Comment by KaKi87** [comment]
Funny, usually it's chinese comments which I stumble upon, from people who, for some reason, think that they can speak their native language in the middle of an international conversation and expect to be understood and replied to.

However, GitHub being an english site doesn't force people to speak english, just like programming languages using english keywords don't force people to write english code.

For example, [a french media app's repo](https://github.com/AnaelMobilia/NextINpact-Unofficial) has no interest in using english since the content is not international, therefore documentation & issues are written in french.

**Comment by Sash0k** [comment]
>However, GitHub being an english site doesn't force people to speak english

@KaKi87, yep. He is totally wrong in that comment.
But, I really prefer to continue discussion in fork repo. Could you migrate this issue description [here](https://github.com/Sash0k/ActivityLauncher/issues)?

**Comment by KaKi87** [comment]
> Please keep meta-discussions out of the issues. Instead, I suggest to create an issue template with guidelines and delete comments that do not follow those.

So you are so uninterested in maintaining your app that you even require PRs from others for community management ?

**Comment by butzist** [comment]
See #51

**Comment by Sash0k** [comment]
> Btw thank you for maintaining a fork of the app. If you have some features that you would like integrated here, feel free to create a PR.

@butzist https://github.com/butzist/ActivityLauncher/issues/193#issuecomment-1431193775
Wont contribute to you because of you discrimintation policy, commit [#958c31d](https://github.com/butzist/ActivityLauncher/commit/958c31db449d9a04d264ed0225e7ebfc6e8a1943)

**Comment by KaKi87** [comment]
If you're talking about [the `1.14.6` tag](https://github.com/butzist/ActivityLauncher/releases/tag/1.14.6) then I confirm the issue is occuring on that very version.

Personally I'm using the main profile.

**Comment by butzist** [comment]
still valid with v2? reopen if necessary
