### ISSUE TITLE
SIM-Manager

### ISSUE THREAD

**Issue by ceresolis** [butzist/ActivityLauncher#194]
Hi there

the sim manager shortcut suddenly stopped working!? Does somebody has any idea?
Samsung Note 20 Ultra, Androud 13, One UI 5.0,

**Comment by drogga** [comment]
#171 #193

**Comment by drogga** [comment]
@ceresolis Only the shortcut or launching the activity from inside the Activity Launcher also doesn't work and have you tried the same with other similar apps to this one ?

**Comment by ceresolis** [comment]
Both, from the shortcut and inside the app. Yes, other activitys works (they with no green lock symbol)
Error: java.lang.SecurityException: Permission Denial: starting Intent ...

**Comment by drogga** [comment]
I asked if you tried to launch it with other apps like this one, but it seems like Samsung made the activity you are trying to launch private, meaning not the app's fault!
