### ISSUE TITLE
0a6259®![IMG_20230213_223751](https://user-images.githubusercontent.com/102030260/218517445-9179dd31-81eb-459c-99b9-26bc443e31b5.jpg)

### ISSUE THREAD

**Issue by IBBLDBLTD** [butzist/ActivityLauncher#200]
![IMG_20230213_223751](https://user-images.githubusercontent.com/102030260/218517445-9179dd31-81eb-459c-99b9-26bc443e31b5.jpg)
> Разработать...Почему нас должно волновать, что телеграмма имеет или не имеет, и как это нас объединяет ?

But Activity Launcher v1.14.0  - shows activities Telegram's...
It turns out your application does not match the description.
"creates shortcuts for ANY installed app and hidden activities to launch them with ease"
No, dont creates for any.

_Originally posted by @fvkras in https://github.com/butzist/ActivityLauncher/issues/196#issuecomment-1428241370_

**Comment by drogga** [comment]
Spam. Should be deleted (I can't) and reported...
