### ISSUE TITLE
[[16259](IBBL.)](4794965093796.4847668293650)

### ISSUE THREAD

**Issue by IBBLDBLTD** [butzist/ActivityLauncher#201]
[[16259](IBBL.)](4794965093796.4847668293650)

_Originally posted by @IBBLDBLTD in https://github.com/butzist/ActivityLauncher/issues/200#issuecomment-1492014482_
Islami Bank Tower 40. Dilkusha C/A .Dhaka-1000. Bangladesh
Developed by : Software Team, Islami Bank Bangladesh Limited.

Copyright © 1983-2021 Islami Bank Bangladesh Limited.
            
![Screenshot_2023-03-26-16-43-16-44_be80aec1db9a2b53c9d399db0c602181](https://user-images.githubusercontent.com/127050727/229155060-50547fb1-4bdc-4060-b4e5-dc5980aeea19.jpg)
![Screenshot_2023-03-26-16-42-48-06_be80aec1db9a2b53c9d399db0c602181](https://user-images.githubusercontent.com/127050727/229155102-40834109-08b2-45cf-b7c3-e726d43a0b08.jpg)
![IMG_20230319_134855](https://user-images.githubusercontent.com/127050727/229155114-66770d14-24e0-483a-801f-6127b538ec9a.jpg)
![IMG-20230109-WA0004](https://user-images.githubusercontent.com/127050727/229155123-fddc4d22-e517-41d0-b1a1-ac81b1be3e62.jpg)
![IMG-20230206-WA0001](https://user-images.githubusercontent.com/127050727/229155130-1757e390-1935-4987-a2b8-288e1586d7e7.jpg)
![IMG-20230216-WA0014](https://user-images.githubusercontent.com/127050727/229155138-f776aa8b-d7cf-4846-bd9e-dcf868900588.jpg)
![IMG-20230120-WA0021](https://user-images.githubusercontent.com/127050727/229155145-c155d20e-e13b-483f-b530-3fcceac4de2d.jpg)

**Comment by drogga** [comment]
Spam.
