### ISSUE TITLE
Dual apps and secondary space  not creating

### ISSUE THREAD

**Issue by Sayvan2018** [butzist/ActivityLauncher#205]
After updating of mi 11i 5g to miui 14, dual apps and secondary space are not creating through activity launcher. Please check the issue once.

**Comment by Lexander217** [comment]
No puedo crear app duales

**Comment by Bikasarkar** [comment]
After updating of mi 11i 5g to miui 14, dual apps and secondary space are not creating through activity launcher. Please check the issue once.

**Comment by Shailesh8287** [comment]
https://github.com/butzist/ActivityLauncher/issues/205#issue-1711657742

**Comment by Shailesh8287** [comment]
Second space and dual app is not working

**Comment by Sayvan2018** [comment]
Then how do I use dual app?
Dual apps are working in all the remaining mobiles having miui 14. Is it
resolvable or not. Please clarify

Thank you
