### ISSUE TITLE
No Webview activity 

### ISSUE THREAD

**Issue by 1flytec** [butzist/ActivityLauncher#209]
Doesn't have Webview
![Screenshot_20230622_125445_Activity Launcher](https://github.com/butzist/ActivityLauncher/assets/89214417/a6cbbb89-a157-4931-b6b0-d81eaacd9633)

**Comment by drogga** [comment]
Probably because it's either disabled or it doesn't have any activities...

**Comment by 1flytec** [comment]
But how to open Webview beta devtools?

**Comment by drogga** [comment]
Enable the WebView first.
Also make sure its App Name\Label is not in Cyrillic (looking at "Bixby ассистент" listing from your screenshot)...

**Comment by drogga** [comment]
@1flytec ...
