### ISSUE TITLE
// im.vector.app.features.link.LinkHandlerActivity - mozilla.components.feature.pwa.WebAppLauncherActivity

### ISSUE THREAD

**Issue by chityin222** [butzist/ActivityLauncher#223]
// im.vector.app.features.link.LinkHandlerActivity - mozilla.components.feature.pwa.WebAppLauncherActivity
Intent intent = new Intent();
intent.setClassName(packageName, activityName);
intent.setData(android.net.Uri.parse(permalink));
ctx.startActivity(intent);

_Originally posted by @chityin222 in https://github.com/butzist/ActivityLauncher/issues/154#issuecomment-1826989689_

**Comment by chityin222** [comment]
// im.vector.app.features.link.LinkHandlerActivity - mozilla.components.feature.pwa.WebAppLauncherActivity
Intent intent = new Intent();
intent.setClassName(packageName, activityName);
intent.setData(android.net.Uri.parse(permalink));
ctx.startActivity(intent);

**Comment by chityin222** [comment]
// im.vector.app.features.link.LinkHandlerActivity - mozilla.components.feature.pwa.WebAppLauncherActivity
Intent intent = new Intent();
intent.setClassName(packageName, activityName);
intent.setData(android.net.Uri.parse(permalink));
ctx.startActivity(intent);

**Comment by butzist** [comment]
@chityin222 would you like to explain what the goal of this code snippet is?
