### ISSUE TITLE
Can't find a few activities listed.

### ISSUE THREAD

**Issue by shivendratrivedi99** [butzist/ActivityLauncher#23]
![Screenshot_2019-11-23-13-43-34-081_com google android googlequicksearchbox](https://user-images.githubusercontent.com/57279618/69475916-16472300-0df9-11ea-9311-dde6f178756e.jpg)
![IMG_20191123_125346](https://user-images.githubusercontent.com/57279618/69475917-16dfb980-0df9-11ea-9bdd-008ba02f0cc6.jpg)
![IMG_20191123_140015](https://user-images.githubusercontent.com/57279618/69475971-9bcad300-0df9-11ea-9d2c-fe21db126d60.jpg)

> Can't find these activities in activity launcher app.

> Can you tell why??

**Comment by butzist** [comment]
I can find com.google.androidapps.gsa.assistant.settings.AssistantSettingsActivity but it would not start. The other one I can not find - but also do not have GLens installed.
