### ISSUE TITLE
Progress bar during initial load

### ISSUE THREAD

**Issue by Terrance** [butzist/ActivityLauncher#250]
In v1, I believe there used to be a progress bar at startup while apps were being indexed.

As of v2, we get either a blank screen or the Android default splash screen with the logo, but there's no visual indication that this indexing is happening (assuming this is indeed the hold-up).  I'm aware the indexing has been improved (ref. #68), though there's still a noticeable delay, and after it hangs for more than a few seconds it gives the impression that it's stuck / in ANR state rather than loading.  It would be slightly nicer for the user to have some kind of feedback past the splash screen to show it's busy, static or otherwise.

**Comment by butzist** [comment]
Agree, had one user who thought the app was stuck because he did not get a splash screen, and he closed it again after two seconds or so.

If nobody provides a PR for this, I will probably add this next time I revisit the app.

**Comment by NikunjKhangwal** [comment]
+1
I also thought the app got stuck

**Comment by drogga** [comment]
It should definitely show how many apps are being loaded (just like before), but probably it would be better to show the packages count next to the "Installed Packages" header, which is probably a bit confusing, given that system apps are listed as well and those can't exactly be considered "installed", so it would probably be better to rename it to remove the "Installed" text from there.

**Comment by butzist** [comment]
@drogga please stop adding unrelated comments to the ticket

**Comment by drogga** [comment]
I probably didn't make this clear enough, but my comment is very much on point and related and not off-topic, at least for the first part to the end of the closing bracket, I've just extended the idea with the following text, it's still very much UI related tho, but OK, I will refrain from commenting further, no problem.

**Comment by butzist** [comment]
I pushed a proposed fix to master - can someone check if it's fixing this issue?

**Comment by NikunjKhangwal** [comment]
> Can someone check if current master fixes this issue?

It does. Great work
