### ISSUE TITLE
Feature requests (or maybe app request)

### ISSUE THREAD

**Issue by bb1a2** [butzist/ActivityLauncher#258]
There are a lot of useful toggles even a non-rooted app has access too on Android. For example, enable/disable "do not disturb", "open notifications" and so on. For an almost exhaustive list of these functions, see [here](https://github.com/sds100/KeyMapper) and [here](https://gitlab.com/asdoi/quick-tiles).

It is similar in principle to what ActivityLauncher provides (a way to access hidden settings). **So I am suggesting that a list of these toggles be available as shortcuts in ActivityLauncher (or a sibling app)**. To my knowledge there is no FOSS app on F-Droid that provides such actions in a user-friendly way. There are the two apps I linked, but one of them is a button mapper that crashes when trying to create a shortcut for the toggle. It is also discontinued. The other is for tiles (Quick Settings) rather than shortcuts.

I think it is worth considering.

**Comment by bb1a2** [comment]
Something like this: https://play.google.com/store/apps/details?id=com.leedroid.shortcutter&hl=en-US

![](https://play-lh.googleusercontent.com/glhx5i_YCNlICoPh-YwZ7RbgrgYaBuHVy8SdLXOowFMGBy53qQeV1a32fpVjf164_w=w2560-h1440)

**Comment by butzist** [comment]
out of scope for this app - but feel free to reuse eg the shortcut creation and launching for another app
