### ISSUE TITLE
crash in landscape (no horizontal scroll bar)

### ISSUE THREAD

**Issue by mmm4m5m** [butzist/ActivityLauncher#27]
Activity Launcher version 1.9.2, Android 9 Pie

If phone is in landscape mode and I start Activity Launcher, then application crash.

If I start Activity Launcher and then turn phone in landscape mode - application crash.

(Long lines go outside the screen, text can not be read, there is no horizontal scroll bar.)

Thanks!

**Comment by slyzilo** [comment]
Its crashing on my samsung galaxy note 8

**Comment by butzist** [comment]
Is this a regression? Let me know when you find a solution and create a pull-request.

**Comment by vaimalaviya1233** [comment]
@butzist @slyzilo @mmm4m5m 
Sorry to say But this issue is Resolved in version 1.10.0 and tested myself on Galaxy note 10+(android 10)
Close this issue 🥳
