### ISSUE TITLE
Java session error

### ISSUE THREAD

**Issue by Clash352** [butzist/ActivityLauncher#285]
I need to enter a function called image engine but it is not entering, it just stays black screen below and a message appears talking about problems with the java session.
please I need to solve this problem

**Comment by drogga** [comment]
It's a private one, that's why, don't you see the padlock icon ?

**Comment by Clash352** [comment]
What do you mean it's in private? I didn't change anything in this app, it's simply not working anymore so I can deactivate the option 😔

**Comment by drogga** [comment]
The developers change the activities attributes, rename/remove them and and new ones, this is not something that is a constant and doesn't change over time. Nothing to do with this app, it's not its fault that an activity can no longer be launched without root (often with root as well) or it's missing.
