### ISSUE TITLE
Update to Android 10 no longer allows me to set RCS flags for Google messages

### ISSUE THREAD

**Issue by vrajkovi** [butzist/ActivityLauncher#30]
After update to Android 10, on a Firstnet Samsung Galaxy S9, I'm no longer able to setup RCS flags for Google messages. 

What it currently does:
![Screenshot_20200304-222547_Activity Launcher](https://user-images.githubusercontent.com/16692844/75948031-ea135780-5e67-11ea-9766-cc5e8afa148f.jpg)

What it's supposed to do:
![20200304_223008](https://user-images.githubusercontent.com/16692844/75948038-eed80b80-5e67-11ea-8d8d-1227ed16fda1.jpg)

**Comment by vrajkovi** [comment]
What happens and shows up currently

![Screenshot_20200304-222547_Activity Launcher](https://user-images.githubusercontent.com/16692844/75947789-34480900-5e67-11ea-985d-50c74fc22864.jpg)

**Comment by vrajkovi** [comment]
What used to, and is supposed to pop up. 
![20200304_223008](https://user-images.githubusercontent.com/16692844/75947988-c8b26b80-5e67-11ea-882d-977b948214c9.jpg)

**Comment by butzist** [comment]
Has been disabled by Google
