### ISSUE TITLE
Wifi Hotspot setting not working

### ISSUE THREAD

**Issue by LimitBreaker7** [butzist/ActivityLauncher#300]
After Samsung One UI 6.1.1 update yesterday on Galaxy Tab S8 (Wifi only version) the setting of turning on a Wifi Hotspot through ActivityLauncher is not working anymore, this was the only way to turn on Wifi Hotspot as this setting in not listed in the regular device settings (because it is Wifi version even though it can do it). I hope this can be fixed by the app or maybe it's worse and Samsung just ended this functionality completely.

**Comment by drogga** [comment]
Oh, I see, they blocked the toggle itself from turning on, definitely not dependent nor has anything to do with any activity launcher, not just this one, as the activity starts just fine.
You can try enabling it with apps like Tasker or with SetEdit (Settings Database Editor), but you will most probably need to allow permissions with an ADB command(s) and I prefer if we don't discuss this here as the ticket will turn off-topic, also I can't help much more.

I don't think forcefully adding the related QuickTile will change anything or maybe even the apps like these 2: 
https://play.google.com/store/apps/details?id=kha.prog.mikrotik
https://play.google.com/store/apps/details?id=netshare.wifihotspot
...you can try tho...

**Comment by LimitBreaker7** [comment]
Thanks I really appreciate it
