### ISSUE TITLE
No set rcs flags

### ISSUE THREAD

**Issue by Toya88** [butzist/ActivityLauncher#32]
I have a Samsung galaxy note 5. I downloaded Google messages and Carrie services.  I followed all the instructions and downloaded the activity launcher,  but i don't have the set rcs flags.  I have joined the beta, cut my Wi-Fi off and restarted my phone but the option still isn't there. How can i fix it?
![Screenshot_20200312-203641](https://user-images.githubusercontent.com/52177401/76581435-506c2b80-64a1-11ea-803a-fa1a8513fbf8.png)

**Comment by muznyo** [comment]
@Toya88 That hack for enabling rcs was disabled by google so it won't work anymore
