### ISSUE TITLE
Settings??

### ISSUE THREAD

**Issue by Simplypassby** [butzist/ActivityLauncher#33]
Hello,
I installed Activity launcher so I could access my kindle fire HD 8 (6th generation) usage data settings. Following instructions online, I was told one could select "all applications" and " settings" to get to this permission. I cannot find either option on the app.
Please help.

**Comment by JonnyTech** [comment]
Search for `usage` in the app, it should find many, then try each one. My phone shows many activities:

![usage](https://user-images.githubusercontent.com/3584732/80861919-61e3df80-8c69-11ea-9e13-258f36b3483e.png)

**Comment by butzist** [comment]
Is this a regression? Let me know when you find a solution and create a pull-request.
