### ISSUE TITLE
Headphone controls and equalizer

### ISSUE THREAD

**Issue by Manuelnr67** [butzist/ActivityLauncher#37]
After Android 10 update the headphone equalizer and controls cannot be found in setting -- sound menú.
Could you please help ??

**Comment by butzist** [comment]
Anything this app can help with? The activity exists but is not listed?

**Comment by vaimalaviya1233** [comment]
@Manuelnr67 @butzist 
If your're on android 10 and on samsung phone it's under SoundAlive app
it's already listed and if not use search "sound" or "equalizer"
issue solved please close the issue
