### ISSUE TITLE
Add Theme Pack Support

### ISSUE THREAD

**Issue by rgocal** [butzist/ActivityLauncher#4]
Would you be able to switch out the drawable chooser to select an installed icon pack and than choose a desired  icon instead.

**Comment by chenweiwei0060** [comment]
requestWindowFeature(Window.FEATURE_NO_TITLE);                    //隱藏標題列
getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,  //隱藏狀態列
                     WindowManager.LayoutParams.FLAG_FULLSCREEN);

**Comment by butzist** [comment]
Let me know when you find a solution and create a pull-request.
