### ISSUE TITLE
Clicking on generated shortcut gives "App isn't installed."

### ISSUE THREAD

**Issue by lma-gh** [butzist/ActivityLauncher#42]
On a Huawei Mate 20 with EMUI 9, a shortcut to
Android's magnification gesture screen gets
generated, but upon clicking on it on the
homescreen, I get a small popup at the bottom
saying "App isn't installed".
.
If it helps: Wenn I just short-click on the activity
in the list of activities, I get a popup complaining
about permission denial of
.
huawei.android.permission.HW_SIGNATURE_OR_SYSTEM
.
However, the shortcut for Android's accessibility screen (so 1 level above the magnification gesture screen) works fine.

**Comment by butzist** [comment]
Sound like Huawei proprietary mechanism preventing you from starting the app... Let me know when you find a solution and create a pull-request.
