### ISSUE TITLE
I did not find this option

### ISSUE THREAD

**Issue by Rachidddz** [butzist/ActivityLauncher#44]
![Screenshot_20201020-024243_Activity Launcher](https://user-images.githubusercontent.com/73148795/96530186-cd088900-127e-11eb-96cf-d14d944e051e.jpg)

**Comment by Rachidddz** [comment]
Helpp

**Comment by Rachidddz** [comment]
I did not find this option

**Comment by Antonchijk** [comment]
@Rachidddz
