### ISSUE TITLE
SD Card as internal storage

### ISSUE THREAD

**Issue by Terminator147** [butzist/ActivityLauncher#45]
Upon formatting my SD card, my phone has filled up all 32GB of it with system storage. On top of that, deleting apps is not making any space for new ones; the storage says that the storage used for apps has reduced but keeps the available storage the same instead of going up. Anyone know how to help?

**Comment by f1vefour** [comment]
Format it as removable storage if you don't want to use it for apps.

This has nothing to do with ActivityLauncher.

**Comment by butzist** [comment]
Issue not related to this app.
