### ISSUE TITLE
Motion Smoothness

### ISSUE THREAD

**Issue by issacg9640** [butzist/ActivityLauncher#46]
It does not work on my S10 rubbing One UI 2.5.

**Comment by smsolaiman1** [comment]
I can't on 120hz refresh rate.thre was no option to on refresh rage

**Comment by Joselu07** [comment]
No funciona el 120fps en mi S10+ ,ni con HD+

**Comment by ahmad483** [comment]
> لا يعمل على S10 فرك One UI 2.5.

متى رح يتم تضمين ٢.٥ ل ١٢٠ هرتز

**Comment by ahmad483** [comment]
يائس

**Comment by butzist** [comment]
Is this a regression? Let me know when you find a solution and create a pull-request.

**Comment by Joselu07** [comment]
No funciona 120hz en samsung s10+
-U.i 3.0 última actualización -
