### ISSUE TITLE
SD formatting

### ISSUE THREAD

**Issue by samSame6** [butzist/ActivityLauncher#61]
Used app to format SD card now SD card does not show on any device does your app come with a warranty?

**Comment by drogga** [comment]
@samSame6 - **Yes, it does !** when you first launch it, there's a warning message prompt\window that appears.
It isn't the app's fault for your mistakes, so please close this. Thanks.
BTW - you shouldn't have used it for this in the first place for this, as the option should be build-in in the UI (menus - onder "storage" options) and not something that you have to look for in the activities, but if for some strange reason it isn't, then stop buying shitty Chinese devices...

Anyway, it's not my job to tell you this, but you can "fix it" by hooking it up to a PC and format to to exFat, or use another android device to format it, even if it doesn't have microSD slot - OTG & Card Reader will do too...

**Comment by drogga** [comment]
@samSame6 - **Yes, it does !** when you first launch it, there's a warning message prompt\window that appears.
It isn't the app's fault for your mistakes, so please close this. Thanks.
BTW - you shouldn't have used it for this in the first place, as the option should be build-in in the UI (menus - under "storage" options) and not something that you have to look for in the activities, but if for some strange reason it isn't, then stop buying\using shitty Chinese devices...

Anyway, it's not my job to tell you this (as I'm nobody), but you can "fix it" by hooking it up to a PC and format it to exFat, or use another android device to format it, even if it doesn't have microSD slot - OTG & Card Reader will do too...
There's even a possibility that your card is dead now.

**Comment by samSame6** [comment]
taken and noted drogga
