### ISSUE TITLE
Google pay shortcut issue

### ISSUE THREAD

**Issue by gaborbit** [butzist/ActivityLauncher#62]
Hi

I have created shortcut for Gpay (settings - Google - account services - Google pay) if launched from the app it works fine but the created shortcut doesn't, it redirects to blank screen

com.google.android.gms.tapandpay.settings.TapAndPaySettingsActivity

Thanks

**Comment by drogga** [comment]
Don't you think that thus is on purpose...!?
Can other similar apps (competitors) that can list and create shortcuts to activities create one that works ?, if not, then you see why ^ and this is probably a pointless issue ticket, so please close it if I'm right...
