### ISSUE TITLE
Crashes with Android 8.0

### ISSUE THREAD

**Issue by mavoga** [butzist/ActivityLauncher#7]
OnePlus3, stock OxygenOS v5.0.0 (Android 8.0)
Activity Launcher v1.6.1 (from F-Droid)

Logcat:
`11-28 22:33:38.851 D/SystemServicesProxy(2198): getRecentTasks: de.szalkowski.activitylauncher, -1, false, 0
11-28 22:33:39.023 D/SystemServicesProxy(2198): getRecentTasks: de.szalkowski.activitylauncher, -1, false, 0
11-28 22:33:40.054 D/TaskView(2198): onClick to 1483, ComponentInfo{de.szalkowski.activitylauncher/de.szalkowski.activitylauncher.MainActivity}
11-28 22:33:40.057 D/SystemServicesProxy(2198): start 1483, ComponentInfo{de.szalkowski.activitylauncher/de.szalkowski.activitylauncher.MainActivity}
11-28 22:33:40.067 I/ActivityManager(1397): checkParallelAppControl, from:net.oneplus.launcher, to:de.szalkowski.activitylauncher, with act:android.intent.action.MAIN, callingUserId:0, toUserId:0
11-28 22:33:40.067 I/ActivityManager(1397): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=de.szalkowski.activitylauncher/.MainActivity (has extras)} from uid 10171 pid -1
11-28 22:33:40.081 D/ActivityTrigger(1397): activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{4544593 de.szalkowski.activitylauncher}
11-28 22:33:40.081 E/ActivityTrigger(1397): activityStartTrigger: not whiteListedde.szalkowski.activitylauncher/de.szalkowski.activitylauncher.MainActivity/10
11-28 22:33:40.082 D/ActivityTrigger(1397): activityResumeTrigger: The activity in ApplicationInfo{4544593 de.szalkowski.activitylauncher} is now in focus and seems to be in full-screen mode
11-28 22:33:40.082 E/ActivityTrigger(1397): activityResumeTrigger: not whiteListedde.szalkowski.activitylauncher/de.szalkowski.activitylauncher.MainActivity/10
11-28 22:33:40.093 D/ActivityTrigger(1397): activityResumeTrigger: The activity in ApplicationInfo{4544593 de.szalkowski.activitylauncher} is now in focus and seems to be in full-screen mode
11-28 22:33:40.093 E/ActivityTrigger(1397): activityResumeTrigger: not whiteListedde.szalkowski.activitylauncher/de.szalkowski.activitylauncher.MainActivity/10
11-28 22:33:40.094 D/EmbryoManager(1397): Embryo claimed. de.szalkowski.activitylauncher, pid=23168
11-28 22:33:40.206 D/SystemServicesProxy(2198): getRecentTasks: de.szalkowski.activitylauncher, 1483, false, 0
11-28 22:33:40.239 I/ActivityManager(1397): Displayed de.szalkowski.activitylauncher/.MainActivity: +142ms
11-28 22:33:40.293 D/SurfaceFlinger(595): duplicate layer name: changing de.szalkowski.activitylauncher/de.szalkowski.activitylauncher.MainActivity to de.szalkowski.activitylauncher/de.szalkowski.activitylauncher.MainActivity#1
11-28 22:33:42.887 D/SurfaceFlinger(595): duplicate layer name: changing de.szalkowski.activitylauncher/de.szalkowski.activitylauncher.MainActivity to de.szalkowski.activitylauncher/de.szalkowski.activitylauncher.MainActivity#1
11-28 22:33:42.924 E/AndroidRuntime(23168): Process: de.szalkowski.activitylauncher, PID: 23168
11-28 22:33:42.924 E/AndroidRuntime(23168): 	at de.szalkowski.activitylauncher.MyPackageInfo.<init>(MyPackageInfo.java:23)
11-28 22:33:42.924 E/AndroidRuntime(23168): 	at de.szalkowski.activitylauncher.PackageManagerCache.getPackageInfo(PackageManagerCache.java:45)
11-28 22:33:42.924 E/AndroidRuntime(23168): 	at de.szalkowski.activitylauncher.AllTasksListAdapter.<init>(AllTasksListAdapter.java:36)
11-28 22:33:42.924 E/AndroidRuntime(23168): 	at de.szalkowski.activitylauncher.AllTasksListAsyncProvider.run(AllTasksListAsyncProvider.java:14)
11-28 22:33:42.924 E/AndroidRuntime(23168): 	at de.szalkowski.activitylauncher.AllTasksListAsyncProvider.run(AllTasksListAsyncProvider.java:5)
11-28 22:33:42.924 E/AndroidRuntime(23168): 	at de.szalkowski.activitylauncher.AsyncProvider.doInBackground(AsyncProvider.java:87)
11-28 22:33:42.924 E/AndroidRuntime(23168): 	at de.szalkowski.activitylauncher.AsyncProvider.doInBackground(AsyncProvider.java:7)
11-28 22:33:42.928 W/ActivityManager(1397):   Force finishing activity de.szalkowski.activitylauncher/.MainActivity
11-28 22:33:42.976 I/ActivityManager(1397): Showing crash dialog for package de.szalkowski.activitylauncher u0
11-28 22:33:43.119 D/SystemServicesProxy(2198): getRecentTasks: de.szalkowski.activitylauncher, -1, false, 0
11-28 22:33:43.575 E/WindowManager(23168): android.view.WindowLeaked: Activity de.szalkowski.activitylauncher.MainActivity has leaked window DecorView@df37f84[] that was originally added here
11-28 22:33:43.575 E/WindowManager(23168): 	at de.szalkowski.activitylauncher.AsyncProvider.onPreExecute(AsyncProvider.java:67)
11-28 22:33:43.575 E/WindowManager(23168): 	at de.szalkowski.activitylauncher.AllTasksListFragment.onCreateView(AllTasksListFragment.java:44)
11-28 22:33:44.194 I/ActivityManager(1397): Killing 23168:de.szalkowski.activitylauncher/u0a234 (adj 902): crash
11-28 22:33:44.197 D/ActivityManager(1397): Process de.szalkowski.activitylauncher has 0 services
11-28 22:33:44.224 D/EmbryoManager(1397): prepare de.szalkowski.activitylauncher user 0
11-28 22:33:45.003 D/SystemServicesProxy(2198): getRecentTasks: de.szalkowski.activitylauncher, -1, false, 0
`

**Comment by sdex** [comment]
there is a better alternative 
https://play.google.com/store/apps/details?id=com.sdex.activityrunner

**Comment by mavoga** [comment]
Nice one, but it's not FOSS AFAICS.


Il 21 maggio 2018 14:55:13 CEST, Yuriy Mysochenko <notifications@github.com> ha scritto:
>there is a better alternative 
>https://play.google.com/store/apps/details?id=com.sdex.activityrunner
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/butzist/ActivityLauncher/issues/7#issuecomment-390645765


--
Inviato dal mio OnePlus 3 con K-9 Mail.
