### ISSUE TITLE
Activity details in hard to read Gray

### ISSUE THREAD

**Issue by jidanni** [butzist/ActivityLauncher#73]
Activity details in hard to read grey. Please use black.

**Comment by vaimalaviya1233** [comment]
@jidanni 
all text colors are in high contrast if you build from GitHub.  dev hasn't updated this high contrast color version in play store

@butzist  playstore update needed thanks

**Comment by vaimalaviya1233** [comment]
@jidanni  hi there's apk built from github action run you can [download ](https://github.com/butzist/ActivityLauncher/runs/2653280281)that artifact it's in zip file extract and there is ap
k inside which you can install( darkmode , high contrast text-colors) you can download from either there or i have attached that zip file in the end of comment 

[Debug (1).zip](https://github.com/butzist/ActivityLauncher/files/6733566/Debug.1.zip)

**Comment by jidanni** [comment]
Thanks, I'm not in that big of a hurry so I'll just get it when it arrives in the new version.

**Comment by butzist** [comment]
Please try the beta release version 1.11 (in review now and should be available in a few days) and let me know if it fixes the issue
