### ISSUE TITLE
List should stay stable when changing phone orientation

### ISSUE THREAD

**Issue by jidanni** [butzist/ActivityLauncher#74]
In the long list of apps, if we open one of them and then turn our cell phone horizontally it gets closed and we arrive back at the top in the page.

For instance tap Play Store and we see a lot of activities.  Now turn your phone horizontally and it all closes back up and we're back in the A's.

**Comment by butzist** [comment]
Orientation has been disabled to work around this issue

**Comment by drogga** [comment]
In older versions (those that didn't crash when rotating) I was able to fix this simply by adding android:configChanges="orientation" under the main activity in the manifest, making it to not reload/refresh.
I would've restrictes/disabled/prevented the rotation in the manifest instead...
