### ISSUE TITLE
Please help me! How to return this indicator?

### ISSUE THREAD

**Issue by MaxPro03** [butzist/ActivityLauncher#87]
![IMG_20211010_215954](https://user-images.githubusercontent.com/68842645/136982528-a061b694-b32c-46dd-aa46-8d7576476ef7.jpg)
![IMG_20211010_220355](https://user-images.githubusercontent.com/68842645/136982557-4f9267e7-c8b7-4b9d-959e-cb71337fcc0d.jpg)

**Comment by drogga** [comment]
...and this is out problem and we should care because !?...
Why and how did you thought that this is related to this app's development !?

Open this one more time and you will *probably* be reported or straight up banned \ blocked from this repo !

**Comment by MaxPro03** [comment]
![Screenshot_2021-10-16-23-05-43-327_de szalkowski activitylauncher](https://user-images.githubusercontent.com/68842645/137597757-cbb1aeb9-3108-40f5-a702-bd465adedd88.jpg)

**Comment by drogga** [comment]
...so it was the SystemUI Tuner all along and you fixed what you broke ?
BTW, there's a disclaimer message at first launch, that writes: 
"Use this software at your own risk. Some apps might not behave as expected when their activities are launched in the wrong context leading to data loss or even worse. You have been warned. Do you understand this and still want to use this software?"
